# Generated by Django 2.1.3 on 2021-06-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(default='', max_length=256, verbose_name='dbname')),
                ('dbtype', models.CharField(default='', max_length=20, verbose_name='dbtype')),
            ],
            options={
                'verbose_name': '二手房',
            },
        ),
    ]
