# Generated by Django 2.1.3 on 2021-06-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(default='human', max_length=256, verbose_name='dbname')),
                ('dbtype', models.CharField(default='core', max_length=20, verbose_name='dbtype')),
            ],
            options={
                'verbose_name': 'datbase',
            },
        ),
    ]
