# Generated by Django 2.1.3 on 2021-06-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='dbname',
            field=models.CharField(default='human', max_length=256, verbose_name='dbname'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='dbtype',
            field=models.CharField(default='core', max_length=20, verbose_name='dbtype'),
        ),
    ]
